# This file was generated by GoReleaser. DO NOT EDIT.
cask "conductor-kit" do
  name "conductor-kit"
  desc "Global skills pack and Go helper for Codex CLI and Claude Code"
  homepage "https://github.com/Skyline-23/conductor-kit"
  version "0.1.54"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "conductor"

  on_macos do
    on_intel do
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v#{version}/conductor-kit_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Skyline-23/conductor-kit"
      sha256 "d909c4caabd0951544d2f231d5caaa834c78cae94432c85d5463033c3207609e"
    end
    on_arm do
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v#{version}/conductor-kit_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Skyline-23/conductor-kit"
      sha256 "59fe7c621626f614eedb05f58dff5526520b1ae791a9cb00e0b657c92708a770"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v#{version}/conductor-kit_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Skyline-23/conductor-kit"
      sha256 "b72e29c9a1efc37b1d03cc17b32ca4317ebe84be4de152ffa07460fcac0d1a2a"
    end
    on_arm do
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v#{version}/conductor-kit_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Skyline-23/conductor-kit"
      sha256 "792d2fbcc8d24470754e4ed60dfc93b82f2cb3fd979bf1bbedc6fc6c151f9b01"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
    system_command "#{staged_path}/conductor", args: ["install", "--mode", "link", "--repo", "#{staged_path}", "--force"]
  end

  uninstall_preflight do
    if File.exist?("#{staged_path}/conductor")
      system_command "#{staged_path}/conductor", args: ["uninstall", "--force"]
    end
  end

  caveats do
    "Skills/commands were linked into ~/.codex and ~/.claude during install."
    "If you need to re-link:"
    "  #{staged_path}/conductor install --mode link --repo #{staged_path} --force"
    "To fully remove user-level installs:"
    "  conductor uninstall --force"
  end

  # No zap stanza required
end
