# This file was generated by GoReleaser. DO NOT EDIT.
cask "conductor-kit" do
  name "conductor-kit"
  desc "Global skills pack and Go helper for Codex CLI and Claude Code"
  homepage "https://github.com/Skyline-23/conductor-kit"
  version "0.1.50"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "conductor"

  on_macos do
    on_intel do
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v#{version}/conductor-kit_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Skyline-23/conductor-kit"
      sha256 "de6cfe29a89f29737309898bf78e1d1cb69ca954a9412e163d6063aca411c9fb"
    end
    on_arm do
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v#{version}/conductor-kit_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Skyline-23/conductor-kit"
      sha256 "0417ba22dd9d65c4fa86b5f55fd411d78a43210638b29f37bbd08511efe90487"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v#{version}/conductor-kit_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Skyline-23/conductor-kit"
      sha256 "8eb000d48e2bbbb4a270c8788a4ec8da59e0a7f16c1d1ef5cad79e0f56c459b1"
    end
    on_arm do
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v#{version}/conductor-kit_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Skyline-23/conductor-kit"
      sha256 "a0458bd511d9116ee1b6d06cdd64a8f476de260137921e6e8d2489ff162b1dc6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
    system_command "#{staged_path}/conductor", args: ["install", "--mode", "link", "--repo", "#{staged_path}", "--force"]
  end

  uninstall_preflight do
    if File.exist?("#{staged_path}/conductor")
      system_command "#{staged_path}/conductor", args: ["uninstall", "--force"]
    end
  end

  caveats do
    "Skills/commands were linked into ~/.codex and ~/.claude during install."
    "If you need to re-link:"
    "  #{staged_path}/conductor install --mode link --repo #{staged_path} --force"
    "To fully remove user-level installs:"
    "  conductor uninstall --force"
  end

  # No zap stanza required
end
