# This file was generated by GoReleaser. DO NOT EDIT.
cask "conductor-kit" do
  name "conductor-kit"
  desc "Global skills pack and Go helper for Codex CLI and Claude Code"
  homepage "https://github.com/Skyline-23/conductor-kit"
  version "0.1.37"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "conductor"

  on_macos do
    on_intel do
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v#{version}/conductor-kit_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Skyline-23/conductor-kit"
      sha256 "413f003e6b79344dd140ac14e10e1f6d05a5716f0cf14b8c3701a767f66ad4a9"
    end
    on_arm do
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v#{version}/conductor-kit_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Skyline-23/conductor-kit"
      sha256 "3bd771b38c26ccc6729e0734f4923286d317d563a5db4ad1615e41998c6e6245"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v#{version}/conductor-kit_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Skyline-23/conductor-kit"
      sha256 "457bcdc023af766aacffed713813cf46a20ca828913fda71ed2f20cefcee4b95"
    end
    on_arm do
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v#{version}/conductor-kit_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Skyline-23/conductor-kit"
      sha256 "7da0411da2dd41d6995ba61934ef0097d082066328841af6da58787e2a2521eb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
    system_command "#{staged_path}/conductor", args: ["install", "--mode", "link", "--repo", "#{staged_path}", "--force"]
  end

  uninstall_preflight do
    if File.exist?("#{staged_path}/conductor")
      system_command "#{staged_path}/conductor", args: ["uninstall", "--force"]
    end
  end

  caveats do
    "Skills/commands were linked into ~/.codex and ~/.claude during install."
    "If you need to re-link:"
    "  #{staged_path}/conductor install --mode link --repo #{staged_path} --force"
    "To fully remove user-level installs:"
    "  conductor uninstall --force"
  end

  # No zap stanza required
end
