# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConductorKit < Formula
  desc "Global skills pack and Go helper for Codex CLI and Claude Code"
  homepage "https://github.com/Skyline-23/conductor-kit"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v0.1.8/conductor-kit_0.1.8_darwin_amd64.tar.gz"
      sha256 "3362bbf32a8144c9dd943307f87769b68e2494beabb9d87e86d2980f1971700f"

      def install
        bin.install "conductor"
        (bin/"conductor-background-task").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-task "$@"
        EOS
        (bin/"conductor-background-output").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-output "$@"
        EOS
        (bin/"conductor-background-cancel").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-cancel "$@"
        EOS
        (bin/"conductor-background-batch").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-batch "$@"
        EOS
        chmod 0755, [bin/"conductor-background-task", bin/"conductor-background-output", bin/"conductor-background-cancel", bin/"conductor-background-batch"]
        pkgshare.install "skills", "commands", "config"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v0.1.8/conductor-kit_0.1.8_darwin_arm64.tar.gz"
      sha256 "a464b683440b1ac9742508ef6995b214cf47a5c559461f84836aebf98b2036f6"

      def install
        bin.install "conductor"
        (bin/"conductor-background-task").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-task "$@"
        EOS
        (bin/"conductor-background-output").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-output "$@"
        EOS
        (bin/"conductor-background-cancel").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-cancel "$@"
        EOS
        (bin/"conductor-background-batch").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-batch "$@"
        EOS
        chmod 0755, [bin/"conductor-background-task", bin/"conductor-background-output", bin/"conductor-background-cancel", bin/"conductor-background-batch"]
        pkgshare.install "skills", "commands", "config"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v0.1.8/conductor-kit_0.1.8_linux_amd64.tar.gz"
      sha256 "7c7ab2c0046c1945db9e7f5c8fc0b8c7e51bf669d7a832b62837cf41b0a864ce"
      def install
        bin.install "conductor"
        (bin/"conductor-background-task").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-task "$@"
        EOS
        (bin/"conductor-background-output").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-output "$@"
        EOS
        (bin/"conductor-background-cancel").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-cancel "$@"
        EOS
        (bin/"conductor-background-batch").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-batch "$@"
        EOS
        chmod 0755, [bin/"conductor-background-task", bin/"conductor-background-output", bin/"conductor-background-cancel", bin/"conductor-background-batch"]
        pkgshare.install "skills", "commands", "config"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v0.1.8/conductor-kit_0.1.8_linux_arm64.tar.gz"
      sha256 "1cf48357d84f75d9676674985d2f8c9bb04c6c17940c019aa4eac9fb00c4bb7e"
      def install
        bin.install "conductor"
        (bin/"conductor-background-task").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-task "$@"
        EOS
        (bin/"conductor-background-output").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-output "$@"
        EOS
        (bin/"conductor-background-cancel").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-cancel "$@"
        EOS
        (bin/"conductor-background-batch").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-batch "$@"
        EOS
        chmod 0755, [bin/"conductor-background-task", bin/"conductor-background-output", bin/"conductor-background-cancel", bin/"conductor-background-batch"]
        pkgshare.install "skills", "commands", "config"
      end
    end
  end

  def post_install
    system "#{bin}/conductor", "install", "--mode", "link", "--repo", "#{pkgshare}", "--force"
  end

  def caveats
    <<~EOS
      Skills/commands were linked into ~/.codex and ~/.claude during install.
      If you need to re-link:
        conductor install --mode link --repo #{pkgshare} --force
    EOS
  end
end
