# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConductorKit < Formula
  desc "Global skills pack and Go helper for Codex CLI and Claude Code"
  homepage "https://github.com/Skyline-23/conductor-kit"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v0.1.5/conductor-kit_0.1.5_darwin_amd64.tar.gz"
      sha256 "5203db9ddb1e1021c364d2ae90b3e26adff7573eca9993cc7769dd35432183f1"

      def install
        bin.install "conductor"
        (bin/"conductor-background-task").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-task "$@"
        EOS
        (bin/"conductor-background-output").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-output "$@"
        EOS
        (bin/"conductor-background-cancel").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-cancel "$@"
        EOS
        (bin/"conductor-background-batch").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-batch "$@"
        EOS
        chmod 0755, [bin/"conductor-background-task", bin/"conductor-background-output", bin/"conductor-background-cancel", bin/"conductor-background-batch"]
        pkgshare.install "skills", "commands", "config"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v0.1.5/conductor-kit_0.1.5_darwin_arm64.tar.gz"
      sha256 "58aa9a4021d85d73dd56ed9b2948b23f940c97fa2e257ae8f4c08d098d6cbade"

      def install
        bin.install "conductor"
        (bin/"conductor-background-task").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-task "$@"
        EOS
        (bin/"conductor-background-output").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-output "$@"
        EOS
        (bin/"conductor-background-cancel").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-cancel "$@"
        EOS
        (bin/"conductor-background-batch").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-batch "$@"
        EOS
        chmod 0755, [bin/"conductor-background-task", bin/"conductor-background-output", bin/"conductor-background-cancel", bin/"conductor-background-batch"]
        pkgshare.install "skills", "commands", "config"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v0.1.5/conductor-kit_0.1.5_linux_amd64.tar.gz"
      sha256 "3e2c1b764544194de9df3c108c10068fa5036ac1cc76e649d7646db01d3193bb"
      def install
        bin.install "conductor"
        (bin/"conductor-background-task").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-task "$@"
        EOS
        (bin/"conductor-background-output").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-output "$@"
        EOS
        (bin/"conductor-background-cancel").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-cancel "$@"
        EOS
        (bin/"conductor-background-batch").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-batch "$@"
        EOS
        chmod 0755, [bin/"conductor-background-task", bin/"conductor-background-output", bin/"conductor-background-cancel", bin/"conductor-background-batch"]
        pkgshare.install "skills", "commands", "config"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Skyline-23/conductor-kit/releases/download/v0.1.5/conductor-kit_0.1.5_linux_arm64.tar.gz"
      sha256 "9fd0c8c8e24e9cc73eba2fed472b72f8b9339d780216c16ecb33d54eb014854f"
      def install
        bin.install "conductor"
        (bin/"conductor-background-task").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-task "$@"
        EOS
        (bin/"conductor-background-output").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-output "$@"
        EOS
        (bin/"conductor-background-cancel").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-cancel "$@"
        EOS
        (bin/"conductor-background-batch").write <<~EOS
          #!/bin/sh
          exec "#{bin}/conductor" background-batch "$@"
        EOS
        chmod 0755, [bin/"conductor-background-task", bin/"conductor-background-output", bin/"conductor-background-cancel", bin/"conductor-background-batch"]
        pkgshare.install "skills", "commands", "config"
      end
    end
  end

  def post_install
    system "#{bin}/conductor", "install", "--mode", "link", "--repo", "#{pkgshare}", "--force"
  end

  def caveats
    <<~EOS
      Skills/commands were linked into ~/.codex and ~/.claude during install.
      If you need to re-link:
        conductor install --mode link --repo #{pkgshare} --force
    EOS
  end
end
